/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** ICE server configuration exposed to JavaScript. */
export interface JsRtcIceServer {
  urls: Array<string>
  username?: string
  credential?: string
  credentialType?: string
}
/** Peer connection configuration exposed to JavaScript. */
export interface JsRtcConfiguration {
  iceServers?: Array<JsRtcIceServer>
  iceTransportPolicy?: string
}
/** Session description exposed to JavaScript. */
export interface JsRtcSessionDescription {
  type: string
  sdp: string
}
/** ICE candidate exposed to JavaScript. */
export interface JsRtcIceCandidate {
  candidate: string
  sdpMid?: string
  sdpMLineIndex?: number
  usernameFragment?: string
}
/** Options for creating a data channel from JavaScript. */
export interface JsRtcDataChannelInit {
  ordered?: boolean
  maxPacketLifeTime?: number
  maxRetransmits?: number
  protocol?: string
  negotiated?: number
}
export declare function version(): string
export type JsRTCDataChannel = JsRtcDataChannel
/** WebRTC data channel exposed to JavaScript. */
export declare class JsRtcDataChannel {
  get label(): string
  get id(): number
  get readyState(): string
  bufferedAmount(): Promise<number>
  send(data: string | Buffer): Promise<void>
  close(): Promise<void>
  setOnOpen(callback: (...args: any[]) => any): void
  setOnMessage(callback: (...args: any[]) => any): void
  setOnClose(callback: (...args: any[]) => any): void
  setOnError(callback: (...args: any[]) => any): void
}
/** Media stream track exposed to JavaScript (stub). */
export declare class JsMediaStreamTrack {
  get id(): string
  get kind(): string
  get streamId(): string
  get enabled(): boolean
  set enabled(enabled: boolean)
}
/** Media stream exposed to JavaScript (stub). */
export declare class JsMediaStream {
  constructor(id: string)
  get id(): string
}
/** Local audio track for sending media to a peer connection. */
export declare class JsLocalAudioTrack {
  constructor(id: string, streamId: string)
  get id(): string
  get kind(): string
  get streamId(): string
  get enabled(): boolean
  set enabled(enabled: boolean)
  /** Writes a PCM audio frame to the track. */
  writeSample(data: Buffer, durationMs: number): Promise<void>
}
/** WebRTC peer connection exposed to JavaScript. */
export declare class JsPeerConnection {
  constructor(config?: JsRtcConfiguration | undefined | null)
  get connectionState(): string
  get iceConnectionState(): string
  get iceGatheringState(): string
  get signalingState(): string
  createOffer(): Promise<JsRtcSessionDescription>
  createAnswer(): Promise<JsRtcSessionDescription>
  setLocalDescription(desc: JsRtcSessionDescription): Promise<void>
  setRemoteDescription(desc: JsRtcSessionDescription): Promise<void>
  addIceCandidate(candidate: JsRtcIceCandidate): Promise<void>
  addTrack(track: JsLocalAudioTrack): Promise<void>
  createDataChannel(label: string, options?: JsRtcDataChannelInit | undefined | null): Promise<JsRtcDataChannel>
  close(): Promise<void>
  gatheringComplete(): Promise<void>
  localDescription(): Promise<JsRtcSessionDescription | null>
  remoteDescription(): Promise<JsRtcSessionDescription | null>
  setOnIceCandidate(callback: (...args: any[]) => any): void
  setOnTrack(callback: (...args: any[]) => any): void
  setOnDataChannel(callback: (...args: any[]) => any): void
  setOnConnectionStateChange(callback: (...args: any[]) => any): void
  setOnIceConnectionStateChange(callback: (...args: any[]) => any): void
  setOnNegotiationNeeded(callback: (...args: any[]) => any): void
}
