/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** ICE server configuration for conference rooms. */
export interface JsIceServer {
  urls: Array<string>
  username?: string
  credential?: string
  credentialType?: string
}
/** Room creation options exposed to JavaScript. */
export interface JsRoomOptions {
  maxParticipants?: number
  iceServers?: Array<JsIceServer>
}
/** Participant summary exposed to JavaScript. */
export interface JsParticipantInfo {
  id: string
  connectionState: string
}
/** Mute scope matching the TypeScript `MuteScope` type. */
export const enum JsMuteScope {
  Global = 'global',
  Listener = 'listener'
}
/** Mute options exposed to JavaScript. */
export interface JsMuteOptions {
  scope: JsMuteScope
  listenerId?: string
}
/** Event payload for participant lifecycle callbacks. */
export interface JsParticipantEvent {
  roomId: string
  participantId: string
}
/** Event payload for participant kick callbacks. */
export interface JsParticipantKickedEvent {
  roomId: string
  participantId: string
  reason?: string
}
/** Event payload for participant mute callbacks. */
export interface JsParticipantMutedEvent {
  roomId: string
  targetId: string
  scope: JsMuteScope
  listenerId?: string
}
/** Event payload for mixing enabled changes. */
export interface JsMixingEnabledChangedEvent {
  roomId: string
  enabled: boolean
}
/** Event payload for room errors. */
export interface JsRoomErrorEvent {
  roomId?: string
  message: string
  code?: string
}
/** ICE server configuration exposed to JavaScript. */
export interface JsRtcIceServer {
  urls: Array<string>
  username?: string
  credential?: string
  credentialType?: string
}
/** Peer connection configuration exposed to JavaScript. */
export interface JsRtcConfiguration {
  iceServers?: Array<JsRtcIceServer>
  iceTransportPolicy?: string
  debug?: boolean
}
/** Offer options (W3C `RTCOfferOptions` subset). */
export interface JsRtcOfferOptions {
  iceRestart?: boolean
  voiceActivityDetection?: boolean
  offerToReceiveAudio?: boolean
  offerToReceiveVideo?: boolean
}
/** Answer options (W3C `RTCAnswerOptions` subset). */
export interface JsRtcAnswerOptions {
  voiceActivityDetection?: boolean
}
/** Session description exposed to JavaScript. */
export interface JsRtcSessionDescription {
  type: string
  sdp: string
}
/** ICE candidate exposed to JavaScript. */
export interface JsRtcIceCandidate {
  candidate: string
  sdpMid?: string
  sdpMLineIndex?: number
  usernameFragment?: string
}
/** Options for creating a data channel from JavaScript. */
export interface JsRtcDataChannelInit {
  ordered?: boolean
  maxPacketLifeTime?: number
  maxRetransmits?: number
  protocol?: string
  negotiated?: number
}
/** Init options for {@link RTCPeerConnection.addTransceiver}. */
export interface JsRtcRtpTransceiverInit {
  direction?: string
}
export declare function version(): string
/** One conference room with participant and mixing controls. */
export declare class JsConferenceRoom {
  /** Returns participant summaries for admin/list APIs. */
  listParticipants(): Promise<Array<JsParticipantInfo>>
  /** Mutes a participant globally or for one listener. */
  muteParticipant(targetId: string, options: JsMuteOptions): Promise<void>
  /** Unmutes a participant globally or for one listener. */
  unmuteParticipant(targetId: string, options: JsMuteOptions): Promise<void>
  /** Enables or disables room-wide mixing. */
  setMixingEnabled(enabled: boolean): Promise<void>
  /** Returns whether room-wide mixing is enabled. */
  isMixingEnabled(): Promise<boolean>
  /** Removes a participant with an optional kick reason. */
  kickParticipant(participantId: string, reason?: string | undefined | null): Promise<void>
  /** Routes a JSON signaling payload through the room. */
  handleSignalingMessage(json: string): Promise<string>
  /** Closes all participants and clears room state. */
  close(): Promise<void>
  /** Registers a callback for participant joined events. */
  setOnParticipantJoined(callback: (...args: any[]) => any): void
  /** Registers a callback for participant left events. */
  setOnParticipantLeft(callback: (...args: any[]) => any): void
  /** Registers a callback for participant kicked events. */
  setOnParticipantKicked(callback: (...args: any[]) => any): void
  /** Registers a callback for participant muted events. */
  setOnParticipantMuted(callback: (...args: any[]) => any): void
  /** Registers a callback for mixing enabled changes. */
  setOnMixingEnabledChanged(callback: (...args: any[]) => any): void
  /** Registers a callback for room error events. */
  setOnError(callback: (...args: any[]) => any): void
}
/** Conference server managing multiple rooms. */
export declare class JsConferenceServer {
  /** Creates an empty conference server. */
  constructor()
  /** Creates a room and returns a handle to it. */
  createRoom(roomId: string, options?: JsRoomOptions | undefined | null): Promise<JsConferenceRoom>
  /** Returns a handle to an existing room, if present. */
  getRoom(roomId: string): Promise<JsConferenceRoom | null>
  /** Lists active room identifiers. */
  listRooms(): Promise<Array<string>>
  /** Destroys a room and tears down all participants. */
  destroyRoom(roomId: string): Promise<void>
}
export type JsRTCDataChannel = JsRtcDataChannel
/** WebRTC data channel exposed to JavaScript. */
export declare class JsRtcDataChannel {
  get label(): string
  get id(): number
  get readyState(): string
  bufferedAmount(): Promise<number>
  send(data: string | Buffer): Promise<void>
  close(): Promise<void>
  setBufferedAmountLowThreshold(threshold: number): void
  setOnBufferedAmountLow(callback: (...args: any[]) => any): void
  setOnOpen(callback: (...args: any[]) => any): void
  setOnMessage(callback: (...args: any[]) => any): void
  setOnClose(callback: (...args: any[]) => any): void
  setOnError(callback: (...args: any[]) => any): void
}
/** Media stream track exposed to JavaScript. */
export declare class JsMediaStreamTrack {
  get id(): string
  get kind(): string
  get streamId(): string
  get enabled(): boolean
  set enabled(enabled: boolean)
  /** Decodes the next inbound Opus RTP packet to stereo PCM (remote audio only). */
  readSample(): Promise<Buffer>
}
/** Media stream exposed to JavaScript (stub). */
export declare class JsMediaStream {
  constructor(id: string)
  get id(): string
}
/** Local audio track for sending media to a peer connection. */
export declare class JsLocalAudioTrack {
  constructor(id: string, streamId: string)
  get id(): string
  get kind(): string
  get streamId(): string
  get enabled(): boolean
  set enabled(enabled: boolean)
  /** Writes interleaved stereo PCM; encoded to the negotiated RTP codec before send. */
  writeSample(data: Buffer, durationMs: number): Promise<void>
}
/** WebRTC peer connection exposed to JavaScript. */
export declare class JsPeerConnection {
  constructor(config?: JsRtcConfiguration | undefined | null)
  get connectionState(): string
  get iceConnectionState(): string
  get iceGatheringState(): string
  get signalingState(): string
  createOffer(options?: JsRtcOfferOptions | undefined | null): Promise<JsRtcSessionDescription>
  createAnswer(options?: JsRtcAnswerOptions | undefined | null): Promise<JsRtcSessionDescription>
  setLocalDescription(desc: JsRtcSessionDescription): Promise<void>
  setRemoteDescription(desc: JsRtcSessionDescription): Promise<void>
  addIceCandidate(candidate: JsRtcIceCandidate): Promise<void>
  addTrack(track: JsLocalAudioTrack): Promise<JsRtpSender>
  removeTrack(sender: JsRtpSender): Promise<void>
  addTransceiver(kind?: string | undefined | null, track?: JsLocalAudioTrack | undefined | null, init?: JsRTCRtpTransceiverInit | undefined | null): Promise<JsRtpTransceiver>
  getTransceivers(): Promise<Array<JsRtpTransceiver>>
  getSenders(): Promise<Array<JsRtpSender>>
  getReceivers(): Promise<Array<JsRtpReceiver>>
  createDataChannel(label: string, options?: JsRtcDataChannelInit | undefined | null): Promise<JsRtcDataChannel>
  close(): Promise<void>
  gatheringComplete(): Promise<void>
  setConfiguration(config: JsRtcConfiguration): Promise<void>
  getConfiguration(): Promise<JsRtcConfiguration>
  restartIce(): Promise<void>
  getStats(): Promise<string>
  localDescription(): Promise<JsRtcSessionDescription | null>
  remoteDescription(): Promise<JsRtcSessionDescription | null>
  setOnIceCandidate(callback: (...args: any[]) => any): void
  setOnTrack(callback: (...args: any[]) => any): void
  setOnDataChannel(callback: (...args: any[]) => any): void
  setOnConnectionStateChange(callback: (...args: any[]) => any): void
  setOnIceConnectionStateChange(callback: (...args: any[]) => any): void
  setOnIceGatheringStateChange(callback: (...args: any[]) => any): void
  setOnSignalingStateChange(callback: (...args: any[]) => any): void
  setOnNegotiationNeeded(callback: (...args: any[]) => any): void
}
/** RTP receiver leg of an {@link RTCRtpTransceiver}. */
export declare class JsRtpReceiver {
  get id(): string
  get kind(): string
}
/** RTP sender returned from {@link RTCPeerConnection.addTrack}. */
export declare class JsRtpSender {
  get id(): string
  /** Replaces the outbound audio track without renegotiation. */
  replaceTrack(track?: JsLocalAudioTrack | undefined | null): Promise<void>
}
/** Unified Plan transceiver (sender + receiver pair). */
export declare class JsRtpTransceiver {
  get mid(): string | null
  get direction(): string
  get currentDirection(): string | null
  get kind(): string
  get stopped(): boolean
  get sender(): JsRtpSender
  get receiver(): JsRtpReceiver
  setDirection(direction: string): Promise<void>
  stop(): Promise<void>
}
