/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'node-webrtc-rust.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./node-webrtc-rust.android-arm64.node')
          } else {
            nativeBinding = require('@node-webrtc-rust/bindings-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'node-webrtc-rust.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./node-webrtc-rust.android-arm-eabi.node')
          } else {
            nativeBinding = require('@node-webrtc-rust/bindings-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'node-webrtc-rust.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./node-webrtc-rust.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@node-webrtc-rust/bindings-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'node-webrtc-rust.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./node-webrtc-rust.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@node-webrtc-rust/bindings-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'node-webrtc-rust.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./node-webrtc-rust.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@node-webrtc-rust/bindings-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'node-webrtc-rust.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./node-webrtc-rust.darwin-universal.node')
      } else {
        nativeBinding = require('@node-webrtc-rust/bindings-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'node-webrtc-rust.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./node-webrtc-rust.darwin-x64.node')
          } else {
            nativeBinding = require('@node-webrtc-rust/bindings-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'node-webrtc-rust.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./node-webrtc-rust.darwin-arm64.node')
          } else {
            nativeBinding = require('@node-webrtc-rust/bindings-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'node-webrtc-rust.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./node-webrtc-rust.freebsd-x64.node')
      } else {
        nativeBinding = require('@node-webrtc-rust/bindings-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'node-webrtc-rust.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./node-webrtc-rust.linux-x64-musl.node')
            } else {
              nativeBinding = require('@node-webrtc-rust/bindings-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'node-webrtc-rust.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./node-webrtc-rust.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@node-webrtc-rust/bindings-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'node-webrtc-rust.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./node-webrtc-rust.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@node-webrtc-rust/bindings-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'node-webrtc-rust.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./node-webrtc-rust.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@node-webrtc-rust/bindings-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'node-webrtc-rust.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./node-webrtc-rust.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@node-webrtc-rust/bindings-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'node-webrtc-rust.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./node-webrtc-rust.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@node-webrtc-rust/bindings-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'node-webrtc-rust.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./node-webrtc-rust.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@node-webrtc-rust/bindings-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'node-webrtc-rust.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./node-webrtc-rust.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@node-webrtc-rust/bindings-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'node-webrtc-rust.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./node-webrtc-rust.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@node-webrtc-rust/bindings-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { JsConferenceRoom, JsConferenceServer, JsMuteScope, JsRtcDataChannel, JsMediaStreamTrack, JsMediaStream, JsLocalAudioTrack, JsPeerConnection, JsRtpReceiver, JsRtpSender, JsRtpTransceiver, JsEventDeliveryMode, JsVadSampleRate, JsSttVendor, JsTtsVendor, JsSpeechEventType, JsVoiceAgent, version } = nativeBinding

module.exports.JsConferenceRoom = JsConferenceRoom
module.exports.JsConferenceServer = JsConferenceServer
module.exports.JsMuteScope = JsMuteScope
module.exports.JsRtcDataChannel = JsRtcDataChannel
module.exports.JsMediaStreamTrack = JsMediaStreamTrack
module.exports.JsMediaStream = JsMediaStream
module.exports.JsLocalAudioTrack = JsLocalAudioTrack
module.exports.JsPeerConnection = JsPeerConnection
module.exports.JsRtpReceiver = JsRtpReceiver
module.exports.JsRtpSender = JsRtpSender
module.exports.JsRtpTransceiver = JsRtpTransceiver
module.exports.JsEventDeliveryMode = JsEventDeliveryMode
module.exports.JsVadSampleRate = JsVadSampleRate
module.exports.JsSttVendor = JsSttVendor
module.exports.JsTtsVendor = JsTtsVendor
module.exports.JsSpeechEventType = JsSpeechEventType
module.exports.JsVoiceAgent = JsVoiceAgent
module.exports.version = version
