/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** ICE server configuration for conference rooms. */
export interface JsIceServer {
  urls: Array<string>
  username?: string
  credential?: string
  credentialType?: string
}
/** Room creation options exposed to JavaScript. */
export interface JsRoomOptions {
  maxParticipants?: number
  iceServers?: Array<JsIceServer>
}
/** Participant summary exposed to JavaScript. */
export interface JsParticipantInfo {
  id: string
  connectionState: string
}
/** Mute scope matching the TypeScript `MuteScope` type. */
export const enum JsMuteScope {
  Global = 'global',
  Listener = 'listener'
}
/** Mute options exposed to JavaScript. */
export interface JsMuteOptions {
  scope: JsMuteScope
  listenerId?: string
}
/** Event payload for participant lifecycle callbacks. */
export interface JsParticipantEvent {
  roomId: string
  participantId: string
}
/** Event payload for participant kick callbacks. */
export interface JsParticipantKickedEvent {
  roomId: string
  participantId: string
  reason?: string
}
/** Event payload for participant mute callbacks. */
export interface JsParticipantMutedEvent {
  roomId: string
  targetId: string
  scope: JsMuteScope
  listenerId?: string
}
/** Event payload for mixing enabled changes. */
export interface JsMixingEnabledChangedEvent {
  roomId: string
  enabled: boolean
}
/** Event payload for room errors. */
export interface JsRoomErrorEvent {
  roomId?: string
  message: string
  code?: string
}
/** Returns version strings for the conference bindings and underlying crate. */
export declare function version(): string
/** One conference room with participant and mixing controls. */
export declare class JsConferenceRoom {
  /** Returns participant summaries for admin/list APIs. */
  listParticipants(): Promise<Array<JsParticipantInfo>>
  /** Mutes a participant globally or for one listener. */
  muteParticipant(targetId: string, options: JsMuteOptions): Promise<void>
  /** Unmutes a participant globally or for one listener. */
  unmuteParticipant(targetId: string, options: JsMuteOptions): Promise<void>
  /** Enables or disables room-wide mixing. */
  setMixingEnabled(enabled: boolean): Promise<void>
  /** Returns whether room-wide mixing is enabled. */
  isMixingEnabled(): Promise<boolean>
  /** Removes a participant with an optional kick reason. */
  kickParticipant(participantId: string, reason?: string | undefined | null): Promise<void>
  /** Routes a JSON signaling payload through the room. */
  handleSignalingMessage(json: string): Promise<string>
  /** Closes all participants and clears room state. */
  close(): Promise<void>
  /** Registers a callback for participant joined events. */
  setOnParticipantJoined(callback: (...args: any[]) => any): void
  /** Registers a callback for participant left events. */
  setOnParticipantLeft(callback: (...args: any[]) => any): void
  /** Registers a callback for participant kicked events. */
  setOnParticipantKicked(callback: (...args: any[]) => any): void
  /** Registers a callback for participant muted events. */
  setOnParticipantMuted(callback: (...args: any[]) => any): void
  /** Registers a callback for mixing enabled changes. */
  setOnMixingEnabledChanged(callback: (...args: any[]) => any): void
  /** Registers a callback for room error events. */
  setOnError(callback: (...args: any[]) => any): void
}
/** Conference server managing multiple rooms. */
export declare class JsConferenceServer {
  /** Creates an empty conference server. */
  constructor()
  /** Creates a room and returns a handle to it. */
  createRoom(roomId: string, options?: JsRoomOptions | undefined | null): Promise<JsConferenceRoom>
  /** Returns a handle to an existing room, if present. */
  getRoom(roomId: string): Promise<JsConferenceRoom | null>
  /** Lists active room identifiers. */
  listRooms(): Promise<Array<string>>
  /** Destroys a room and tears down all participants. */
  destroyRoom(roomId: string): Promise<void>
}
